kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod o+w /drone/src
- name: test
  image: node:12
  user: node  
  commands:
  - npm install
  - npm test
- name: docker 
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-record-import-transformer-identifier-services
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: secret
name: docker_username
data: ibl5gVCPqnL8ACkdUxM+xHIoCc/GPMUHC0u+M4mpGaZ/bZxQ+slVXH575vWDi65AZ2U=
---
kind: secret
name: docker_password
data: DJ/tj7STq1UbGSTMot/Mpb9yJBVW2RLAQUfT/Hgfq7dMHmhjoUO8iPIWWX0MuspiG9XNl6bcNfxoElR1hP/Rpxx1j33qH5gFyQoHi3og9XyE0ezqIuoZzTdkA8s=
